.gitignore

Upstream does not have vendor/ checked into their repository, but we need
it in OCP. Add a comment about that.

Add comment about vendoring in OCP fork.

---

Dockerfile.openshift
Dockerfile.openshift.rhel7

Fixes this error when starting driver pods:
`Error: container create failed: time="2020-04-03T08:51:26Z" level=error msg="container_linux.go:349: starting container process caused \"exec: \\\"/usr/bin/aws-ebs-csi-driver\\\": stat /usr/bin/aws-ebs-csi-driver: no such file or directory\""`

carry: Fix binary location source

---

pkg/cloud/cloud.go
pkg/cloud/cloud_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1810470

Bug 1810470:Make EBS controllerexpansion idempotent

---

pkg/cloud/cloud.go
pkg/cloud/cloud_test.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1810470
cc @openshift/sig-storage

Bug 1810470: Drop optimizing check from resizing call

---

pkg/cloud/cloud.go
pkg/cloud/cloud_test.go

When returning successful for volume expansion requests we should
verify both volume size reported via DescribeVolume and pending volume
modifications requests

Bug 1810470: Verify pending volume modifications and size both

---

pkg/cloud/cloud.go

Without checking for optimizing state the resizing operation takes far
too long and hence we are going to bring it back.
The reason for bringing optimizing check back is the root cause of previous flake was volume was entering desired size before it was done being modified (so `describeVolume` reports higher size while volume is still being modified), so optimizing state was not root of the problem. 
On the other hand - *not* checking for optimizing state makes resizing very slow 
This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1810470

Bug 1810470: carry: Check for optimizing state too

---

pkg/driver/controller.go
pkg/driver/controller_test.go
pkg/util/util.go
pkg/util/util_test.go

Backport of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/550 to be more explicit when unsupported volume capabilities are defined.

Bug 1871683: UPSTREAM: 550: Clarify error message when unsupported volume capabilities are provided

---

Dockerfile.openshift.rhel7

Updating ose-aws-ebs-csi-driver builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-aws-ebs-csi-driver.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating ose-aws-ebs-csi-driver builder & base images to be consistent with ART

---

cmd/main.go
cmd/options/controller_options.go
cmd/options_test.go
pkg/cloud/cloud.go
pkg/cloud/cloud_test.go
pkg/driver/controller.go
pkg/driver/controller_test.go
pkg/driver/driver.go
pkg/driver/driver_test.go
pkg/driver/validation.go
pkg/driver/validation_test.go

This adds tags to snapshots so that they can be deleted on cluster deletion.
CC @openshift/storage

Bug 1876935: UPSTREAM: 568: Apply extra volume tags to EBS snapshots

---

Dockerfile
Makefile
hack/verify-all
hack/verify-vendor.sh

**What is this PR about? / Why do we need it?**
Backports most of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/555/.  I couldn't pull this down as a single patch (due to all of the vendor changes), but I cherry-pick'd most of the individual commits and then removed the previous `verify-deps` job from the Makefile in a separate commit.
**What testing is done?** 
Confirmed the `make verify-vendor` and `make verify` jobs ran without failure.

Bug 1872251: Upstream: 555: Vendor deps

---

.ci-operator.yaml
Dockerfile.openshift.rhel7

Reconciling with https://github.com/openshift/ocp-build-data/tree/0059e470a61eba28225165168b22d9e77c33c926/images/ose-aws-ebs-csi-driver.yml
replaces https://github.com/openshift/aws-ebs-csi-driver/pull/194
/cc @openshift/storage

Updating ose-aws-ebs-csi-driver images to be consistent with ART

---

Dockerfile.openshift
Dockerfile.openshift.rhel7

**Is this a bug fix or adding new feature?**
/type bug
**What is this PR about? / Why do we need it?**
﻿The Makefile now defines ARCH?=amd64 which is used to define GOARCH,
which breaks the builds on other arches (namely arm64, given this is for
AWS).
Without this, 4.10 and 4.11 CI on AWS turned solid red.

Bug 2050173: Fix build on ARM after rebase

---

pkg/cloud/cloud.go

Currently, setting the AWS_EC2_ENDPOINT environment variable overwrites the STS endpoint as well. This patch adds a custom
resolver to only set a custom endpoint on EC2 service.
CC @openshift/storage

OCPBUGS-1574: UPSTREAM: 1398: Add resolver to handle custom endpoints

---

pkg/cloud/metadata.go
pkg/cloud/metadata_ec2.go
pkg/cloud/metadata_interface.go
pkg/cloud/metadata_k8s.go
pkg/cloud/metadata_test.go
pkg/cloud/mock_metadata.go
pkg/cloud/volume_limits.go
pkg/driver/node.go
pkg/driver/node_test.go

This commit fixes the `getVolumesLimit` function.
Previously, the volume limit for Nitro instances was based off of a regex. This regex is insufficient for the wide variety of Nitro instances that AWS supports today.
Nitro instances share attachments with ENIs and NVMe instance stores.
The number of attached ENIs is queried through IMDS, against the `network/interfaces/macs` endpoint.
The number of already attached block devices is also queried through IMDS, against the `block-device-mapping` endpoint.
Currently, IMDS does not provide a way to query NVMe instance store volumes. So, all instances that support NVMe instance stores are listed in `pkg/cloud/volume_limits.go`
This commit also added more tests to cover various scenarios.

OCPBUGS-4185: Fix nodeService.getVolumesLimit() adding more instance

---

go.mod
vendor/modules.txt

This is intended to fix the following error:
```
$ go list -mod readonly -m all
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
```
CC @openshift/storage

STOR-1019: Pin k8s.io/dynamic-resource-allocation to v0.26.1

---

go.mod
go.sum
vendor/golang.org/x/text/internal/language/language.go
vendor/golang.org/x/text/internal/language/parse.go
vendor/golang.org/x/text/language/parse.go
vendor/modules.txt

To fix CVE-2021-38561. This fix was merged upstream as part of commit cee57ef595a25b23f8068058fd93f52e2ca63f82, "Update driver dependencies" and we got it to 4.12 as part of rebase.
@openshift/storage

OCPBUGS-12932: 4.11: Bump golang.org/x/text

---

go.mod
go.sum
vendor/modules.txt

The patch to be dropped on the nearest CSI driver rebase (upstream aws-ebs CSI driver does not depend on goproxy since v1.19.0).
The PR removing goproxy deps upstream: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1602
The content of this patch resulted from:
```
$ go get -u github.com/elazarl/goproxy@f99041a5c0273fcf6a144498b458a630585872f; go mod tidy; go mod vendor
```
where `f99041a5c` is commit-id corresponding to https://github.com/elazarl/goproxy/pull/507 which resolved CVE-2023-37788

OCPBUGS-16491: UPSTREAM: <drop>: Bump goproxy to resolve CVE-2023-37788

---

pkg/driver/mock_mount.go
pkg/driver/mount.go
pkg/driver/mount_linux.go
pkg/driver/mount_windows.go
pkg/driver/node.go
pkg/driver/node_test.go
pkg/driver/sanity_test.go
pkg/mounter/README
pkg/mounter/safe_mounter_windows.go

https://issues.redhat.com/browse/OCPBUGS-19069
- UPSTREAM: 1193: Platform agnostic device removal
- UPSTREAM: 1597: Check for 'not mounted' in linux Unstage/Unpublish
- UPSTREAM: 1605: idempotent unmount from NodeUnstageVolume / NodeUnpublishVolume
/cc @openshift/storage @gnufied

[release-4.11] OCPBUGS-19069: Volume unmount repeats after successful unmount, preventing pod delete

---

go.mod
go.sum
vendor/golang.org/x/crypto/ssh/channel.go
vendor/golang.org/x/crypto/ssh/client.go
vendor/golang.org/x/crypto/ssh/handshake.go
vendor/golang.org/x/crypto/ssh/server.go
vendor/golang.org/x/crypto/ssh/transport.go
vendor/modules.txt

/hold for upstream fix to merge
/cc @openshift/storage

OCPBUGS-25500: UPSTREAM: 1877: CVE-2023-48795: bump golang.org/x/crypto to v0.17.0

---

hack/generate-gpu-count-table.sh
hack/generate-instance-store-table.sh
pkg/cloud/volume_limits.go
pkg/driver/node.go
pkg/driver/node_test.go

Cherry-pick of https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2108 and https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/2115

OCPBUGS-37088: UPSTREAM: 2108, 2115: Fix allocatable volumes count for vt1 and g4

---

.ci-operator.yaml
Dockerfile.openshift.rhel7

https://issues.redhat.com/browse/OCPBUGS-40959
This is https://github.com/openshift/aws-ebs-csi-driver/pull/275 with `make update` to add the header back to `.ci-operator.yaml` so the verify job will pass.
/cc @openshift/storage

OCPBUGS-40959: Updating ose-aws-ebs-csi-driver-container image to be consistent with ART for 4.18

---

.ci-operator.yaml
Dockerfile.openshift.rhel7

This is https://github.com/openshift/aws-ebs-csi-driver/pull/279 from the ART bot + `make update` to add the header back to `.ci-operator.yaml` to get past the verify failure.
/cc @openshift/storage

OCPBUGS-45562: Updating ose-aws-ebs-csi-driver-container image to be consistent with ART for 4.19
